### ISSUE TITLE
"aborted by HtmlUnit: Attempted to refresh a page using an ImmediateRefreshHandler which could have caused an OutOfMemoryError Please use WaitingRefreshHandler or ThreadedRefreshHandler instead"

### ISSUE THREAD

**Issue by rb2k** [Nerian/akephalos2#13]
I seem to get a strange error while trying to automate an installation of acquia commons (a drupal distribution).

> (druby://127.0.0.1:56235) /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/akephalos2-2.0.2/lib/akephalos/client.rb:93:in `visit': java.lang.RuntimeException: Refresh to http://127.0.0.1:8888/install.php?locale=&profile=drupal_commons&id=1&op=do_nojs (0s) aborted by HtmlUnit: Attempted to refresh a page using an ImmediateRefreshHandler which could have caused an OutOfMemoryError Please use WaitingRefreshHandler or ThreadedRefreshHandler instead. (NativeException)

**Comment by Nerian** [comment]
Weird error :)

Checkout the refresh_handler branch. Let me know if that fixes it.

Thanks for reporting!

**Comment by rb2k** [comment]
So far:

```
RuntimeError: Could not find html-unit/htmlunit-VERSION.jar in load path:
  [  vendor,
/Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/lib,
/Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/vendor,
file:/Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/1.8,
file:/Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/site_ruby/shared,
file:/Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/jruby-jars-1.6.4/lib/jruby-stdlib-1.6.4.jar!/META-INF/jruby.home/lib/ruby/1.8,
.
  ]
v( root) at /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/lib/akephalos/htmlunit.rb:7
  require at org/jruby/RubyKernel.java:1038
  require at /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/lib/akephalos/htmlunit.rb:29
   (root) at /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/lib/akephalos/client.rb:8
  require at org/jruby/RubyKernel.java:1038
   (root) at /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/bundler/gems/akephalos2-3afeed1080cf/lib/akephalos/client.rb:3
```

I guess this is caused by using bundler, it probably doesn't check out htmlunit properly

My current gem file:

```
source :rubygems
gem 'akephalos2', :require => 'akephalos', :git => "git://github.com/Nerian/akephalos2.git", :branch => "refresh_handler"
```

**Comment by Nerian** [comment]
Try with:  

```
gem 'akephalos2', 
    :require => 'akephalos', 
    :git => "git://github.com/Nerian/akephalos2.git", 
    :branch => "refresh_handler", 
    :submodules => true
```

**Comment by rb2k** [comment]
That solved it, the test-run is working fine now ;)
Not sure what that actually means though.

**Comment by Nerian** [comment]
Great :)

When you clone a git repository submodules are not checkout by default. We need to `git submodule update --init`. 

`:submodule => true` makes bundler execute `git submodule update --init`, which downloads all submodules. In our case, that means it is going to download `vendor/html-unit`.

I will push a gem new version now that it works :)
