### ISSUE TITLE
no such file to load -- jruby-jars 

### ISSUE THREAD

**Issue by rb2k** [Nerian/akephalos2#14]
> /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/akephalos2-2.0.2/bin/akephalos:76:in `require': no such file to load -- jruby-jars (LoadError)
>     from /Users/mseeger/.rvm/gems/ruby-1.8.7-p334/gems/akephalos2-2.0.2/bin/akephalos:76

On 1.8.7-p334, I fixed it by just adding  

> require 'rubygems'

right above it.

**Comment by Nerian** [comment]
Oh, sure. In 1.8.x rubygems is not loaded. 

I'll add it again so that it remains compatible.

**Comment by Nerian** [comment]
New gem is up, Thanks!
