### ISSUE TITLE
Encoding changes from 2.0.6 to 2.0.7

### ISSUE THREAD

**Issue by rb2k** [Nerian/akephalos2#18]
For some reason I have tests passing in 2.0.6 that fail in 2.0.7

This string seems to cause problems: "uʍop ǝpısdn ɯ,ı 'ǝɯ ʇɐ ʞooן |"

In 2.0.6 : pass
In 2.0.7: error

expected "[...]u\303\212\302\215op \303\207\302\235p\303\204\302\261sdn \303\211\302\257,\303\204\302\261 '\303\207\302\235\303\211\302\257 \303\212\302\207\303\211\302\220 \303\212\302\236oo\303\227\302\237\n[...]" to include "u\312\215op \307\235p\304\261sdn \311\257,\304\261 '\307\235\311\257 \312\207\311\220 \312\236oo\327\237"

side by side (a = what I want, b = what I got back from akephalos)

```
a: u\312\215op \307\235p\304\261sdn \311\257,\304\261 '\307\235\311\257 \312\207\311\220 \312\236oo\327\237
b: u\303\212\302\215op \303\207\302\235p\303\204\302\261sdn \303\211\302\257,\303\204\302\261 '\303\207\302\235\303\211\302\257 \303\212\302\207\303\211\302\220 \303\212\302\236oo\303\227\302\237
```

p.s. this is on 1.8.7, I'll try to create a minimal testing example

**Comment by Nerian** [comment]
From 2.0.7 Akephalos is using JRuby with --1.9. That means the encoding of strings is UTF-8.

What ruby version are you using?

Do you have `# encoding: utf-8` at the start of the file in which yours test are?

**Comment by Nerian** [comment]
Check f8df95a19a90c05d75bf5eac8c72fc317a0c0516

**Comment by rb2k** [comment]
Since the string is in a cucumber feature (-> not ruby), I'm not 100% sure where to add the encoding flag...

I'm using ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-darwin10.7.4]

**Comment by Nerian** [comment]
Put it a the very first line of the file of the cucumber file

**Comment by rb2k** [comment]
No changes. Seeing as the feature file is actually "Gerkin" and gets parsed, I don't know if adding that line would have any results in general

**Comment by Nerian** [comment]
Try with env.rb

**Comment by rb2k** [comment]
Nope, also no luck with the step definition

**Comment by Nerian** [comment]
I just found this http://katrinaowen.com/2010/12/17/encoding-issues-cucumber

**Comment by rb2k** [comment]
She used 1.9, that's something that I don't do (for now). But I'll keep looking into iconv and others

**Comment by rb2k** [comment]
Works fine in 1.9 without any changes btw

**Comment by Nerian** [comment]
I am glad to know that. I am looking to a quick way to make it configurable for the moment. But notice that support for 1.8 in Akephalos will be dropped in a couple of months.

The whole 1.8.x branch will be out of support.
http://redmine.ruby-lang.org/issues/4996

So, why is she using 1.8? Can't she just upgrade to 1.9?

**Comment by rb2k** [comment]
I'm using 1.8 mainly because puppet doesn't run properly on on 1.9 and our CI server uses puppet. Might be time to look into getting RVM running on it... :-/

**Comment by Nerian** [comment]
I added the option to use JRuby in 1.8 mode. 

Just set ENV['JRUBY_1_8'] to true.

That is implemented in the 'encoding' branch. Check it out and see if it solves the problem :)

I agree, time to order a new puppet for Christmas  :)

**Comment by rb2k** [comment]
YAY! That solved it :)
It is passing using that branch and the env car set

**Comment by Nerian** [comment]
Perfect :)

Version up and pushing new gem.

Now we are just 4 errors from having a clean test suite :)
