### ISSUE TITLE
"Could not find htmlunit/htmlunit-VERSION.jar in load path"

### ISSUE THREAD

**Issue by rb2k** [Nerian/akephalos2#2]
I get this when running with the new akephalos2 gem: 

```
RuntimeError: Could not find htmlunit/htmlunit-VERSION.jar in load path:
  [ vendor,
    /vol/ebs1/jenkins/jobs/xxxxxx/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.0.0/lib,
    /vol/ebs1/jenkins/jobs/xxxxxx/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.0.0/src,
    .,
```

Did the gemspec somehow miss that?

**Comment by Nerian** [comment]
Oh no, the gemspec should be fine.

The problem should be here.
https://github.com/Nerian/akephalos2/blob/master/lib/akephalos/htmlunit.rb

That is trying to load the jar from the old path, 'src' instead of the new one 'vendor'.

I will look into it now.

**Comment by rb2k** [comment]
thanks! glad to see you're in a similar timezone :)

**Comment by Nerian** [comment]
Here was the problem :)

https://github.com/Nerian/akephalos2/commit/db3670929262a2de66992eedeed70693082f388e

I am pushing a new gem now. Let me know if that fix the problem. 

Thanks for reporting!

**Comment by rb2k** [comment]
seems to work, thanks :)
