### ISSUE TITLE
htmlunit_downloader.rb:28:in `<': comparison of Fixnum with String failed

### ISSUE THREAD

**Issue by rb2k** [Nerian/akephalos2#26]
The recent update seems to have borked akephalos on my CI setup

```
parallel/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/lib/akephalos/htmlunit_downloader.rb:28:in `<': comparison of Fixnum with String failed (ArgumentError)
from /[...]/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/lib/akephalos/htmlunit_downloader.rb:28:in `download'
from /[...]/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/lib/akephalos/htmlunit_downloader.rb:7:in `download_htmlunit'
from /[...]/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/bin/akephalos:30
from /usr/lib/ruby/1.8/optparse.rb:791:in `initialize'
from /[...]/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/bin/akephalos:11:in `new'
from /[...]/workspace/src/vendor/bundle/ruby/1.8/gems/akephalos2-2.1.1.1/bin/akephalos:11
```

**Comment by Nerian** [comment]
What ENV["htmlunit_version"] have you set?

**Comment by Nerian** [comment]
Oh I think I know what is happening. You are using the Akephalos binary directly, right?

**Comment by Nerian** [comment]
Checkout master

**Comment by rb2k** [comment]
I am not using the binary directly, running it as a regular require, managing it using bundler
I didn't set any htmlunit_version
I'll try it again with master, but I currently have a batch tests running on our CI machine with 2.0.9

**Comment by Nerian** [comment]
I refactored the code so that is more robust. Try master again.

**Comment by Nerian** [comment]
Basically now akephalos downloads HTMLUnit on demand, instead of having it distributed on the code. 

So the first time that you use Akephalos, it is going to download the default HtmlUnit 2.9. You can configure it using the environmental variable `htmlunit_version`.

**Comment by Nerian** [comment]
So how did it go?

**Comment by Nerian** [comment]
Closing this for now. Let me know if it still persist.
