### ISSUE TITLE
use unzip instead of tar

### ISSUE THREAD

**Issue by mclassen** [Nerian/akephalos2#27]
Using tar xzf to unpack a zip-file doesn't work.

Therefore, in lib/akephalos/htmlunit_downloader.rb:20:

```
`tar xzf htmlunit-#{version}.zip`
```

should be changed to:

```
`unzip -j htmlunit-#{version}.zip`
```

**Comment by Nerian** [comment]
It works on my Mac OS Lion box. I guess you are using Linux, right? The behaviour of Tar is different between OS then.

I will change it.

**Comment by Nerian** [comment]
Checkout 2.1.1.2, now it is using unzip.

Thanks for reporting :+1:

**Comment by mclassen** [comment]
Actually, that fix doesn't work for me either, but I played around with it some more, I think the self.unzip method should actually look like this:

```
def self.unzip(version)
  `unzip -j -d .akephalos/#{version} htmlunit-#{version}.zip`
end
```

Mind the -j and -d .akephalos/#{version} bit!

I think you actually don't need the moving of the jar files, if you just extract everything in the right directory (i.e.  .akephalos/#{version}) right away...

I don't even think you need to treat version 2.10 differently here, since you used the same file format when downloading it (using the -o option).

So, this should work in theory for 2.10 and 2.9 and below. It seems to work fine on my Linux machine.

**Comment by Nerian** [comment]
Good point. Code changed,

```
gem 'akephalos2', :git => 'git://github.com/Nerian/akephalos2.git'
```

Let me know if that build in Linux.

**Comment by Nerian** [comment]
Closing this for now. Let me know if you still have problems.
